import type { AssignableUser } from '@/types';
import type { FunnelWheelStage } from '@/Components/FunnelStageWheelPicker.vue';

export type ChatHeaderDialogsContext = {
    departmentModalOpen: boolean;
    closeDepartmentModal: () => void;
    departmentSearchQuery: string;
    filteredDepartments: Array<{ id: number; name: string }>;
    selectedDepartmentIds: number[];
    toggleDepartment: (id: number) => void;
    savingDepartments: boolean;
    openDepartmentHistoryModal: () => void | Promise<void>;
    departmentHistoryModalOpen: boolean;
    closeDepartmentHistoryModal: () => void;
    loadDepartmentHistory: () => void | Promise<void>;
    departmentHistoryLoading: boolean;
    departmentHistoryError: string | null;
    departmentHistory: Array<{ id: number; body: string; at: string | null }>;
    currentDepartmentsHistory: Array<{ id: number; name: string }>;
    assignmentModalOpen: boolean;
    closeAssignmentModal: () => void;
    userSearchQuery: string;
    filteredAssignableUsers: AssignableUser[];
    selectedUserIds: number[];
    toggleUser: (id: number) => void;
    savingUsers: boolean;
    openAssignmentHistoryModal: () => void | Promise<void>;
    assignmentHistoryModalOpen: boolean;
    closeAssignmentHistoryModal: () => void;
    loadAssignmentHistory: () => void | Promise<void>;
    assignmentHistoryLoading: boolean;
    assignmentHistoryError: string | null;
    assignmentHistory: Array<{ id: number; body: string; at: string | null }>;
    currentAssignmentsHistory: Array<{ id: number; user_id: number; user_name: string | null; assigned_by_name: string | null; assigned_at: string | null }>;
    formatAssignmentTime: (value: string | null) => string;
    assignableUserRoleLine: (u: AssignableUser) => string;
    funnelModalOpen: boolean;
    closeFunnelModal: () => void;
    funnelCatalogList: Array<{ id: number; name: string; stages?: Array<{ id: number; name: string; color?: string | null; stage_type?: string | null; position?: number }> }>;
    funnelModalFunnelId: number | null;
    funnelModalStageId: number | null;
    funnelModalTracking: boolean;
    funnelModalLocked: boolean;
    funnelSaving: boolean;
    onFunnelSelect: (e: Event) => void;
    modalStagesOrdered: FunnelWheelStage[];
    modalStageIndex: number;
    modalFunnelColor: string;
    modalFunnelSegmentStyle: (cellIndex: number, color: string) => Record<string, string>;
    funnelWheelRef: { scrollToStage: (id: number | null) => void; refresh: () => void } | null;
    saveFunnelModal: () => void | Promise<void>;
    funnelHistoryLoading: boolean;
    funnelHistoryError: string | null;
    funnelHistory: Array<{ id: number; source: string; reason: string | null; confidence: number | null; created_at: string | null; to_funnel_id: number | null; to_stage_id: number | null }>;
    aiRiskyEnableModalOpen: boolean;
    aiRiskyEnableModal: {
        message: string;
        warnings: string[];
        readinessScore: number | null;
        settingsUrl: string;
    } | null;
    aiRiskyEnableConfirming: boolean;
    closeAiRiskyEnableModal: () => void;
    confirmAiRiskyEnable: () => void | Promise<void>;
};